package com.uit.melodydiary.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF5E3AE7)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE6DEFF)
val md_theme_light_onPrimaryContainer = Color(0xFF1B0063)
val md_theme_light_secondary = Color(0xFF006D3E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF96F7B7)
val md_theme_light_onSecondaryContainer = Color(0xFF00210F)
val md_theme_light_tertiary = Color(0xFF616200)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE8E970)
val md_theme_light_onTertiaryContainer = Color(0xFF1C1D00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFD7F9FA)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFD7F9FA)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE5E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF48454E)
val md_theme_light_outline = Color(0xFF79757F)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFC9BEFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF5E3AE7)
val md_theme_light_outlineVariant = Color(0xFFC9C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFC9BEFF)
val md_theme_dark_onPrimary = Color(0xFF2F009B)
val md_theme_dark_primaryContainer = Color(0xFF4611D0)
val md_theme_dark_onPrimaryContainer = Color(0xFFE6DEFF)
val md_theme_dark_secondary = Color(0xFF7BDA9D)
val md_theme_dark_onSecondary = Color(0xFF00391E)
val md_theme_dark_secondaryContainer = Color(0xFF00522D)
val md_theme_dark_onSecondaryContainer = Color(0xFF96F7B7)
val md_theme_dark_tertiary = Color(0xFFCBCC58)
val md_theme_dark_onTertiary = Color(0xFF323200)
val md_theme_dark_tertiaryContainer = Color(0xFF494900)
val md_theme_dark_onTertiaryContainer = Color(0xFFE8E970)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF48454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC9C5D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inversePrimary = Color(0xFF5E3AE7)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFC9BEFF)
val md_theme_dark_outlineVariant = Color(0xFF48454E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF613EEA)

val mygreen = Color(0xFFa4f5ca)
val mauDa1 = Color(0xFFfbf2d5)
val mauDa2 = Color(0xFFfce6ce)
val mauDa3 = Color(0xFFc0ecc8)
val mauDa4 = Color(0xFFcddeb2)
val mauDa5 = Color(0xFFdaf7f5)
val mauDa6 = Color(0xFFebe2fd)
val mauDa7 = Color(0xFFebe2fd)
val musicItemColor = Color(0xFFEAE7D6)
